name: 'Changelog'
description: 'Generate and commit CHANGELOG.md'
inputs:
  token:
    description: Personal access token
    default: ${{ github.token }}
    required: false

runs:
  using: 'composite'
  steps:
    - uses: ory/ci/checkout@master
      with:
        token: ${{ inputs.token }}
        fetch-depth: 0
    - name: set up the Git client
      run: |
        git config --global user.email "60093411+ory-bot@users.noreply.github.com"
        git config --global user.name "ory-bot"
      shell: bash
    - name: create the changelog
      run: |
        curl -sSfL https://raw.githubusercontent.com/ory/ci/master/changelog/create_changelog.sh | bash
      shell: bash
    - name: commit the changes
      if: ${{ github.ref_name == "master" || github.ref_type == "tag" }}
      env:
        GITHUB_TOKEN: ${{ inputs.token || github.token }}
      run: |
        branch="$(date +%s)"
        git checkout -b "$branch" || true
        git add CHANGELOG.md || true
        git commit -m "autogen(docs): regenerate and update changelog" -m "[skip ci]" || true
        git pull origin master --rebase || true
        git push origin HEAD:master || true
      shell: bash
