name: 'Docs CLI (Next Generation)'
description: 'Build CLI docs and commit to ory/docs'
inputs:
  token:
    description: Personal access token
    default: ${{ github.token }}
    required: false
  docs-branch:
    description: On which ory/docs branch to operate on
    default: 'master'
    required: false
  arg:
    description: Optional additional argument to .bin/clidoc (inserted before output-dir)
    default: ''
    required: false
  output-dir:
    description: Directory without leading slash in ory/docs to write the CLI docs to
    required: true

runs:
  using: "composite"
  steps:
    - uses: ory/ci/checkout@master
      with:
        token: ${{ inputs.token || github.token }}
        path: current-repo
        fetch-depth: 0
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - run: |
        git config --global user.email "60093411+ory-bot@users.noreply.github.com"
        git config --global user.name "ory-bot"
      shell: bash
    - run: echo 'GOPATH='"$(go env GOPATH)" >> $GITHUB_ENV
      shell: bash

    - uses: actions/checkout@v2
      with:
        repository: ory/docs
        path: docs
        ref: ${{ inputs.docs-branch }}
        fetch-depth: 0
        token: ${{ inputs.token || github.token  }}

    - name: Build and push CLI docs
      shell: bash
      run: |
        cd current-repo
        make .bin/clidoc
        .bin/clidoc ${{ inputs.arg }} ../docs/${{ inputs.output-dir }}

    - uses: ory/ci/prettier@master
      with:
        dir: docs
        action: write
        target: ${{ inputs.output-dir }}

    - name: Push docs
      if: ${{ github.ref_name == 'master' || github.ref_type == 'tag' }}
      shell: bash
      run: |
        cd docs
        if [[ -z "$(git status --porcelain)" ]]; then
          echo "Nothing to commit"
          exit 0
        fi
        git add -A
        git stash
        git pull --rebase origin ${{ inputs.docs-branch }}
        git stash apply
        git commit -a -m "autogen(docs): generate cli docs"
        git push origin ${{ inputs.docs-branch }}
