name: "Generate license overview"
description: "List and check licenses"

runs:
  using: "composite"
  steps:
    - name: List and write licenses
      run: |
        mkdir -p .reports
        .bin/list-licenses > .reports/dep-licenses.csv
      shell: bash
    - name: Commit result
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        (git commit -m "autogen: update license overview" && git push) || true
      shell: bash
