name: "Generate license overview"
description: "List and check licenses"

inputs:
  author-email:
    description: "Author email for git commits"
    required: true
  author-name:
    description: "Author name for git commits"
    required: true

runs:
  using: "composite"
  steps:
    - name: List and write licenses
      run: |
        mkdir -p .reports
        .bin/list-licenses > .reports/dep-licenses.csv
      shell: bash
    - name: Commit result
      run: |
        git config --global user.email "${{ inputs.author-email }}"
        git config --global user.name "${{ inputs.author-name }}"
        git add .
        git commit -m "autogen: update license overview" || true
        git pull -ff || true
        git push
      shell: bash
