name: 'License checker and lister'
description: 'List and check licenses'
input:
  token:
    description: Personal access token
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        # We must fetch at least the immediate parents so that if this is
        # a pull request then we can checkout the head.
        fetch-depth: 2
        token: ${{ inputs.token }}
    - uses: actions/setup-go@v3
      with:
        go-version: "1.22"
    - uses: actions/setup-node@v2
      with:
        node-version: "18"
    - name: Install license scanner
      run: curl https://raw.githubusercontent.com/ory/ci/master/licenses/install | sh
      shell: bash
    - name: List and write licenses
      run: |
        mkdir -p .reports
        .bin/list-licenses > .reports/dep-licenses.csv
      shell: bash
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
    - name: Commit Milestone Documentation
      if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
      uses: EndBug/add-and-commit@v9.1.4
      with:
        message: "autogen(docs): update milestone document"
        author_name: aeneasr
        author_email: "3372410+aeneasr@users.noreply.github.com"
    - name: Check licenses
      run: .bin/licenses
      shell: bash
<