name: 'Docs CLI'
description: 'Build CLI docs'
inputs:
  token:
    description: Personal access token
    default: ${{ github.token }}
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        path: current-repo
        fetch-depth: 0
    - uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - run: |
        git config --global user.email "60093411+ory-bot@users.noreply.github.com"
        git config --global user.name "ory-bot"
      shell: bash
    - run: echo 'GOPATH='"$(go env GOPATH)" >> $GITHUB_ENV
      shell: bash
    - name: Build and push CLI docs
      shell: bash
      run: |
        cd current-repo
        make .bin/clidoc
        .bin/clidoc .
    - uses: ory/ci/prettier@master
      with:
        dir: current-repo/docs
        action: write
    - run: |
        cd current-repo
        echo "::set-output name=msg::$(git log --format=%B -n1)"
      shell: bash
      id: commit-msg
    - if: ${{ !startsWith(steps.commit-msg.outputs.msg, 'autogen') }}
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      shell: bash
      run: |
        cd current-repo
        git add -A
        git commit -a -m "autogen(docs): generate cli docs" || true
    - if: ${{ github.ref_type == 'branch' }}
      run: |
        cd current-repo
        git pull --rebase origin "${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"
        git push origin HEAD:"${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}" || true
      shell: bash
    - if: ${{ github.ref_type == 'tag' }}
      run: |
        cd current-repo
        git pull --rebase origin master || true
        git push origin HEAD:master || true
      shell: bash
