name: "Docs CLI"
description: "Build CLI docs"
inputs:
  token:
    description: Personal access token
    default: ${{ github.token }}
    required: false

runs:
  using: "composite"
  steps:
    - if: ${{ github.event_name == 'pull_request' }}
      uses: ory/ci/checkout@master
      with:
        path: current-repo
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        token: ${{ inputs.token || github.token }}
    - if: ${{ github.event_name != 'pull_request' }}
      uses: ory/ci/checkout@master
      with:
        token: ${{ inputs.token || github.token }}
        path: current-repo
        fetch-depth: 0
    - uses: actions/setup-go@v2
      with:
        go-version: "1.21"
    - run: |
        git config --global user.email "60093411+ory-bot@users.noreply.github.com"
        git config --global user.name "ory-bot"
      shell: bash
    - run: echo 'GOPATH='"$(go env GOPATH)" >> $GITHUB_ENV
      shell: bash
    - name: Build and push CLI docs
      shell: bash
      run: |
        cd current-repo
        make .bin/clidoc
        .bin/clidoc .
    - uses: ory/ci/prettier@master
      with:
        dir: current-repo/docs
        action: write
    - env:
        GITHUB_TOKEN: ${{ inputs.token || github.token }}
      if: ${{ github.ref_name == 'master' || github.ref_type == 'tag' }}
      shell: bash
      run: |
        cd current-repo
        git add -A
        git commit -a -m "autogen(docs): generate cli docs" -m "[skip ci]" || true
    - if: ${{ github.ref_name == 'master' || github.ref_type == 'tag' }}
      env:
        GITHUB_TOKEN: ${{ inputs.token || github.token }}
      run: |
        cd current-repo
        git stash || true
        git pull --rebase origin master || true
        git stash apply || true
        git push origin HEAD:master || true
      shell: bash
