#!/usr/bin/sh

unknown=$(cat - | \
grep -v '\bMIT\b' | \
grep -v '\bApache-2.0\b' | \
grep -v '\bBSD-3-Clause\b' | \
grep -v '\bBSD-2-Clause\b' | \
grep -v '\bISC\b' | \
grep -v '\bMPL-2.0\b' | \
grep -v '\bCC0-1.0\b' | \
grep -v '\bgithub.com/ory/kratos-client-go\b' | \
grep -v '\bgithub.com/gobuffalo/github_flavored_markdown\b'
)
if [ -n "$unknown" ]; then
  echo "Unknown licenses found!"
  echo "$unknown"
  exit 1
else
  echo "Licenses are okay."
fi
