#!/bin/sh
set -e

# Default mono-install to false
FULL_INSTALL=false

# Parse command line arguments
while [ "$#" -gt 0 ]; do
    case "$1" in
        --full-install)
            FULL_INSTALL=true
            shift
            ;;
        *)
            echo "Unknown parameter: $1"
            exit 1
            ;;
    esac
done

{
    echo
    echo "Installing license checker engine ..."
    echo
} 2>/dev/null

if [ ! -d .bin ]; then
    mkdir .bin
fi

curl https://raw.githubusercontent.com/ory/ci/master/licenses/license-engine.sh -o .bin/license-engine.sh
chmod +x .bin/license-engine.sh
curl https://raw.githubusercontent.com/ory/ci/master/licenses/licenses -o .bin/licenses
chmod +x .bin/licenses
curl https://raw.githubusercontent.com/ory/ci/master/licenses/list-licenses -o .bin/list-licenses
chmod +x .bin/list-licenses

if [ "$FULL_INSTALL" = true ] || [ -f go.mod ]; then
    {
        echo
        echo "Installing the Go license checker ..."
        echo
    } 2>/dev/null
    GOBIN=$(pwd)/.bin go install github.com/google/go-licenses@master
    curl https://raw.githubusercontent.com/ory/ci/master/licenses/license-template-go.tpl -o .bin/license-template-go.tpl
fi

if [ "$FULL_INSTALL" = true ] || [ -f package.json ]; then
    {
        echo
        echo "Installing the Node license checker ..."
        echo
    } 2>/dev/null
    curl https://raw.githubusercontent.com/ory/ci/master/licenses/license-template-node.json -o .bin/license-template-node.json
fi