#!/bin/sh
set +x

# check Node licenses
if [ -f package.json ]; then
	{ echo "Checking Node licenses ..."; } 2>/dev/null
	npx --yes -- license-checker --csv --production --customPath .bin/license-template-node.json | .bin/check-licenses
	{ echo; } 2>/dev/null
fi

# check Go licenses
if [ -f go.mod ]; then
	{ echo "Checking Go licenses ..."; } 2>/dev/null
	module_name=$(grep "^module" go.mod | awk '{print $2}')
	if [ -z "$module_name" ]; then
		echo "Cannot determine the Go module name"
		exit 1
	fi
	.bin/go-licenses report "$module_name" --template .bin/license-template-go.tpl 2>/dev/null | .bin/check-licenses
	{ echo; } 2>/dev/null
fi
