#!/bin/sh
set -e

bin_dir="$(cd "$(dirname "$0")" && pwd)"

# list Node licenses
if [ -f package.json ]; then
    if jq -e '.dependencies and (.dependencies | keys | length > 0)' package.json > /dev/null; then
				npm install > /dev/null 2>&1
        npm exec --yes license-checker -- --production --csv --excludePrivatePackages --customPath "${bin_dir}"/license-template-node.json | grep -v '^$'
        { echo; } 2>/dev/null
    else
        echo "No dependencies found in package.json" >&2
    fi
fi

# list Go licenses
if [ -f go.mod ]; then
	module_name=$(grep "^module" go.mod | awk '{print $2}')
	if [ -z "$module_name" ]; then
		echo "Cannot determine the Go module name" >&2
		exit 1
	fi

	# Workaround until https://github.com/google/go-licenses/issues/307 is fixed
	# .bin/go-licenses report "$module_name" --template .bin/license-template-go.tpl 2>/dev/null
	# go list -f "{{if not .Indirect}}{{.Path}}{{end}}" -m ... | xargs -I {} sh -c '"${bin_dir}"/go-licenses report --template "${bin_dir}"/license-template-go.tpl {}' 2>/dev/null | grep -v '^$'
	"${bin_dir}"/go-licenses report "$module_name" --template "${bin_dir}"/license-template-go.tpl 2>/dev/null | grep -v '^$'
	{ echo; } 2>/dev/null
fi
