name: "Check license compliance"
runs:
  using: "composite"
  steps:
    - name: Install license scanner
      run: |
        sh "$GITHUB_ACTION_PATH/../install" \
          --source-dir "$GITHUB_ACTION_PATH/.."
      shell: bash
    - name: Check licenses
      run: .bin/licenses
      shell: bash
