name: "Check license compliance"
runs:
  using: "composite"
  steps:
    - name: Install license scanner
      run: |
        ORY_CI_ROOT="${{ github.action_path }}/../.." \
          sh "${{ github.action_path }}/../install"
      shell: bash
    - name: Check licenses
      run: .bin/licenses
      shell: bash
