name: 'SDK Generate'
description: 'SDK generation automation'
inputs:
  token:
    description: Personal access token
    required: false
    default: ${{ github.token }}
outputs:
  sdk-cache-key:
    description: Cache key for the generated SDK
    value: ${{ steps.cache-sdk.outputs.cache-key }}

runs:
  using: "composite"
  steps:
    - if: ${{ github.event_name == 'pull_request' }}
      uses: ory/ci/checkout@master
      with:
        path: current-repo
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        token: ${{ inputs.token || github.token }}
    - if: ${{ github.event_name != 'pull_request' }}
      uses: ory/ci/checkout@master
      with:
        path: current-repo
        token: ${{ inputs.token || github.token }}
    - uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - run: |
        git config --global user.email "60093411+ory-bot@users.noreply.github.com"
        git config --global user.name "ory-bot"
      shell: bash
    - run: echo 'GOPATH='"$(go env GOPATH)" >> $GITHUB_ENV
      shell: bash
    - run: |
        cd current-repo
        wget https://github.com/go-swagger/go-swagger/releases/latest/download/swagger_linux_amd64 \
          -O "$GOPATH/bin/swagger"
        chmod +x "$GOPATH/bin/swagger"
        bash <(curl https://raw.githubusercontent.com/ory/meta/master/install.sh) -b $GOPATH/bin ory
      shell: bash
    - env:
        GITHUB_TOKEN: ${{ inputs.token || github.token }}
      run: |
        cd current-repo
        make sdk
        # Hack to ensure actions/cache uses the same path
        # as the caller.
        mkdir ../internal
        cp -R internal/httpclient ../internal
      shell: bash
    - uses: actions/cache@v2
      with:
        path: |
          internal/httpclient
        key: sdk-${{ github.run_id }}-${{ hashFiles('internal/httpclient/**') }}
    - run: |
        key="sdk-${{ github.run_id }}-${{ hashFiles('internal/httpclient/**') }}"
        echo "::set-output name=cache-key::$key"
      id: cache-sdk
      shell: bash
    - env:
        GITHUB_TOKEN: ${{ inputs.token || github.token }}
      if: ${{ github.ref_name == 'master' || github.ref_type == 'tag' }}
      run: |
        cd current-repo
        git add -A
        git commit -a -m "autogen(openapi): regenerate swagger spec and internal client" -m "[skip ci]" || true
      shell: bash
    - if: ${{ github.ref_name == 'master' || github.ref_type == 'tag' }}
      env:
        GITHUB_TOKEN: ${{ inputs.token || github.token }}
      run: |
        cd current-repo
        git stash || true
        git pull --rebase origin master || true
        git stash apply || true
        git push origin HEAD:master || true
      shell: bash
