version: 2.1
description: Creates and updates the CHANGELOG.md file

executors:
  default:
    docker:
      -
        image: circleci/node:13

jobs:
  generate:
    executor: default
    parameters:
      gitemail:
        description: The git committer's email
        type: string
        default: aeneas@ory.sh
      gitusername:
        description: The git committer's username
        type: string
        default: aeneasr
      commitmessage:
        description: The git commit message
        type: string
        default: "autogen(docs): regenerate and update changelog"
    steps:
      - checkout
      - run: |
          if [[ "$(git show -s --format=%B | head -n 1)" == "autogen"* ]]; then
              circleci-agent step halt
          fi
      - run: git config --global user.email "<<parameters.gitemail>>"
      - run: git config --global user.name "<<parameters.gitusername>>"
      - run:
          name: Generate changelog
          command: "bash <(curl -s https://raw.githubusercontent.com/ory/ci/master/src/scripts/changelog/generate.sh)"
      - run: |
          (git add -A && git commit -m "<<parameters.commitmessage>>" -- CHANGELOG.md && git push origin HEAD:$CIRCLE_BRANCH) || true

examples:
  changelog:
    description: Generate and commit the changelog
    usage:
      version: 2.1
      orbs:
        changelog: ory/changelog@0.0.0
      workflows:
        generate:
          jobs:
            - changelog/changelog
