version: 2.1
description: Run gloangci tools

executors:
  default:
    docker:
      - image: cimg/go:1.16-node
        environment:
          GOPROXY: 'https://proxy.golang.org,direct'

commands:
  check-format:
    steps:
      - run:
          command: "bash <(curl -s https://raw.githubusercontent.com/ory/ci/master/src/scripts/docs/check_format.sh)"

jobs:
  cli:
    executor: default
    steps:
      - checkout
      -
        run:
          name: Build and push CLI docs
          command: "bash <(curl -s https://raw.githubusercontent.com/ory/ci/master/src/scripts/docs/cli.sh)"

  build:
    parameters:
      swag-spec-location:
        description: Location where the Swagger spec should be saved to.
        type: string
        default: .schema/api.swagger.json
      swag-spec-ignore:
        description: Packages to ignore when generating the Swagger spec (space delimited).
        type: string
        default: internal/httpclient
    executor: default
    steps:
      - checkout
      - run:
          name: Build and publish documentation
          command: "bash <(curl -s https://raw.githubusercontent.com/ory/ci/master/src/scripts/docs/build.sh)"
          environment:
            SWAG_SPEC_LOCATION: <<parameters.swag-spec-location>>
            SWAG_SPEC_IGNORE: <<parameters.swag-spec-ignore>>

examples:
  docs:
    description: Run doc tasks
    usage:
      version: 2.1
      orbs:
        foo: ory/doc@0.0.1
      workflows:
        build:
          jobs:
            - doc/build
