version: 2.1
description: Run gloangci tools

executors:
  default:
    docker:
      -
        image: circleci/golang:1.14
        environment:
          - GO111MODULE=on

jobs:
  lint:
    executor: default
    steps:
      - checkout
      - checkout
      -
        restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      -
        run: go mod download
      -
        save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      -
        run: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0
      -
        run: golangci-lint run

examples:
  nancy:
    description: Test go.mod for CVEs using nancy
    usage:
      version: 2.1
      orbs:
        foo: ory/nancy@0.0.1
      workflows:
        lint:
          jobs:
            - golangci/lint
