version: 2.1
description: Helpers for goreleaser

executors:
  default:
    docker:
      -
        image: oryd/xgoreleaser:latest
        environment:
          GOPROXY: 'https://proxy.golang.org,direct'
  node:
    docker:
      -
        image: cimg/go:1.16-node
        environment:
          GOPROXY: 'https://proxy.golang.org,direct'

commands:
  install:
    steps:
      - restore_cache:
          keys:
            - v1-goreleaser-0.184.0
      - run: mkdir -p ~/.bin
      - run: bash <(curl -s https://raw.githubusercontent.com/ory/ci/master/src/scripts/releaser/install.sh) ~/.bin v1.1.0
      - save_cache:
          key: v1-goreleaser-0.184.0
          paths:
            - ~/.bin
  check:
    steps:
      - run:
          command: PATH=$HOME/.bin:$PATH goreleaser check

jobs:
  release:
    parameters:
      gitauthtoken:
        description: A GitHub API Token
        type: env_var_name
        default: GITHUB_TOKEN
      dockeruser:
        description: The Docker Hub Username
        type: env_var_name
        default: DOCKER_USERNAME
      dockerkey:
        description: The Docker Hub Access Token
        type: env_var_name
        default: DOCKER_TOKEN
      docker-org:
        description: The Docker Organization Name
        type: string
        default: oryd
    executor: default
    working_directory: /home/ory
    steps:
      - checkout
      - setup_remote_docker
      -
        run: docker login --username "${<<parameters.dockeruser>>}" --password "${<<parameters.dockerkey>>}"
      -
        run:
          name: Build and publish the release
          command: "bash <(curl -s https://raw.githubusercontent.com/ory/ci/master/src/scripts/releaser/release.sh)"
          no_output_timeout: 30m

  release-test:
    parameters:
      gitauthtoken:
        description: A GitHub API Token
        type: env_var_name
        default: GITHUB_TOKEN
      dockeruser:
        description: The Docker Hub Username
        type: env_var_name
        default: DOCKER_USERNAME
      dockerkey:
        description: The Docker Hub Access Token
        type: env_var_name
        default: DOCKER_TOKEN
      docker-org:
        description: The Docker Organization Name
        type: string
        default: oryd
    executor: default
    working_directory: /home/ory
    steps:
      - checkout
      -
        run:
          name: Test the release
          command: "bash <(curl -s https://raw.githubusercontent.com/ory/ci/master/src/scripts/releaser/test.sh)"

  newsletter-draft:
    parameters:
      chimp-segment:
        description: The Mailchimp Segment ID
        type: integer
        default: 6477717
      chimp-list:
        description: The Mailchimp List ID
        type: string
        default: 50ec2c014c
    executor: node
    steps:
      - checkout
      -
        run:
          name: Generate changelog and send newsletter
          environment:
            MAILCHIMP_SEGMENT_ID: <<parameters.chimp-segment>>
            MAILCHIMP_LIST_ID: <<parameters.chimp-list>>
          command: |
            bash <(curl -s https://raw.githubusercontent.com/ory/ci/master/src/scripts/releaser/campaign-draft.sh)

  newsletter-send:
    parameters:
      chimp-list:
        description: The Mailchimp List ID
        type: string
        default: 50ec2c014c
    executor: node
    steps:
      - checkout
      -
        run:
          name: Generate changelog and send newsletter
          command: "bash <(curl -s https://raw.githubusercontent.com/ory/ci/master/src/scripts/releaser/campaign-send.sh)"
          environment:
            MAILCHIMP_LIST_ID: <<parameters.chimp-list>>

  test:
    executor: default
    working_directory: /home/ory
    steps:
      - checkout
      - check

  release-dry:
    executor: default
    working_directory: /home/ory
    steps:
      - checkout
      - setup_remote_docker
      - run: goreleaser --snapshot --skip-publish --rm-dist

  render-version-schema:
    parameters:
      schema-path:
        description: The relative path to the config schema from the repository root
        type: string
        default: .schema/config.schema.json
    executor: default
    working_directory: /home/ory
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: "bash <(curl -sL https://raw.githubusercontent.com/ory/ci/master/src/scripts/releaser/render-version-schema.sh)"
          environment:
            SCHEMA_PATH: <<parameters.schema-path>>

examples:
  goreleaser:
    description: Build pipeline. Please check https://github.com/ory/meta/blob/master/docs/releasing.md
    usage:
      version: 2.1
      orbs:
        foo: ory/goreleaser@0.0.0
      workflows:
        release:
          jobs:
            - goreleaser/release
        test:
          jobs:
            - goreleaser/test
        release-dry:
          jobs:
            - goreleaser/release-dry
