version: 2.1
description: Helpers for goreleaser

executors:
  default:
    docker:
      -
        image: circleci/golang:1.13
        environment:
          - GO111MODULE=on

jobs:
  release:
    parameters:
      gitauthtoken:
        description: A GitHub API Token
        type: env_var_name
        default: GITHUB_TOKEN
      dockeruser:
        description: The Docker Hub Username
        type: env_var_name
        default: DOCKER_USERNAME
      dockerkey:
        description: The Docker Hub Access Token
        type: env_var_name
        default: DOCKER_TOKEN
    executor: default
    steps:
      # This needs to run first or we'll override the go.mod file.
      -
        run: go get github.com/goreleaser/goreleaser@v0.124.1

      - checkout
      - setup_remote_docker
      -
        run: docker login --username "${<<parameters.dockeruser>>}" --password "${<<parameters.dockerkey>>}"
      -
        run: |
          source <(curl -s https://raw.githubusercontent.com/ory/ci/master/src/scripts/release_name.sh)
          GITHUB_TOKEN="${<<parameters.gitauthtoken>>}" goreleaser

  test:
    executor: default
    steps:
      # This needs to run first or we'll override the go.mod file.
      -
        run: go get github.com/goreleaser/goreleaser@v0.124.1

      - checkout
      -
        run: goreleaser check

examples:
  goreleaser:
    description: Generate and commit the SDK
    usage:
      version: 2.1
      orbs:
        foo: ory/goreleaser@0.0.0
      workflows:
        release:
          jobs:
            - goreleaser/release
        test:
          jobs:
            - goreleaser/test