version: 2.1
description: Helpers for goreleaser

executors:
  default:
    docker:
      -
        image: oryd/xgoreleaser:1.13.5
        environment:
          - GO111MODULE=on

jobs:
  release:
    parameters:
      gitauthtoken:
        description: A GitHub API Token
        type: env_var_name
        default: GITHUB_TOKEN
      dockeruser:
        description: The Docker Hub Username
        type: env_var_name
        default: DOCKER_USERNAME
      dockerkey:
        description: The Docker Hub Access Token
        type: env_var_name
        default: DOCKER_TOKEN
    executor: default
    steps:
      - checkout
      - setup_remote_docker
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y libc6-dev-i386 gcc-6-arm-linux-gnueabihf
      - run: docker login --username "${<<parameters.dockeruser>>}" --password "${<<parameters.dockerkey>>}"
      - run: curl -sL https://raw.githubusercontent.com/ory/ci/master/src/scripts/release_name.sh | bash > $BASH_ENV
      - run: source $BASH_ENV
      - run: GITHUB_TOKEN="${<<parameters.gitauthtoken>>}" goreleaser

  test:
    executor: default
    steps:
      - checkout
      - run: go mod tidy
      - run: git diff --exit-code
      -
        run: goreleaser check

  release-dry:
    executor: default
    steps:
      - checkout
      - setup_remote_docker
      -
        run: RELEASE_NAME=${CIRCLE_SHA1} goreleaser --snapshot --skip-publish --rm-dist

examples:
  goreleaser:
    description: Generate and commit the SDK
    usage:
      version: 2.1
      orbs:
        foo: ory/goreleaser@0.0.0
      workflows:
        release:
          jobs:
            - goreleaser/release
        test:
          jobs:
            - goreleaser/test
        release-dry:
          jobs:
            - goreleaser/release-dry
