version: 2.1
description: Helpers for goreleaser

executors:
  default:
    docker:
      -
        image: oryd/xgoreleaser:1.14.2-0.131.1
        environment:
          - GO111MODULE=on
  node:
    docker:
      -
        image: circleci/golang:1.14-node
        environment:
          - GO111MODULE=on

jobs:
  release:
    parameters:
      gitauthtoken:
        description: A GitHub API Token
        type: env_var_name
        default: GITHUB_TOKEN
      dockeruser:
        description: The Docker Hub Username
        type: env_var_name
        default: DOCKER_USERNAME
      dockerkey:
        description: The Docker Hub Access Token
        type: env_var_name
        default: DOCKER_TOKEN
      docker-org:
        description: The Docker Organization Name
        type: string
        default: oryd
    executor: default
    working_directory: /home/ory
    steps:
      - checkout
      - setup_remote_docker
      -
        run: docker login --username "${<<parameters.dockeruser>>}" --password "${<<parameters.dockerkey>>}"
      -
        run:
          name: Build and publish the release
          command: "bash <(curl -s https://raw.githubusercontent.com/ory/ci/master/src/scripts/releaser/release.sh)"

      -
        run:
          name: Test the release
          command: "bash <(curl -s https://raw.githubusercontent.com/ory/ci/master/src/scripts/releaser/test.sh)"

  newsletter-draft:
    parameters:
      chimp-segment:
        description: The Mailchimp Segment ID
        type: integer
        default: 6477717
      chimp-list:
        description: The Mailchimp List ID
        type: string
        default: 50ec2c014c
    executor: node
    steps:
      - checkout
      -
        run:
          name: Generate changelog and send newsletter
          environment:
            MAILCHIMP_SEGMENT_ID: <<parameters.chimp-segment>>
            MAILCHIMP_LIST_ID: <<parameters.chimp-list>>
          command: |
            bash <(curl -s https://raw.githubusercontent.com/ory/ci/master/src/scripts/releaser/campaign-draft.sh)

  newsletter-send:
    parameters:
      chimp-list:
        description: The Mailchimp List ID
        type: string
        default: 50ec2c014c
    executor: node
    steps:
      - checkout
      -
        run:
          name: Generate changelog and send newsletter
          command: "bash <(curl -s https://raw.githubusercontent.com/ory/ci/master/src/scripts/releaser/campaign-send.sh)"
          environment:
            MAILCHIMP_LIST_ID: <<parameters.chimp-list>>

  test:
    executor: default
    working_directory: /home/ory
    steps:
      - checkout
      -
        run: go mod download
      -
        run: git diff --exit-code
      -
        run: goreleaser check

  release-dry:
    executor: default
    working_directory: /home/ory
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          curl -sL https://raw.githubusercontent.com/ory/ci/master/src/scripts/release_name.sh | bash > $BASH_ENV
          source $BASH_ENV
          goreleaser --snapshot --skip-publish --rm-dist

  render-version-schema:
    executor: default
    working_directory: /home/ory
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          curl -sL https://raw.githubusercontent.com/ory/ci/master/src/scripts/releaser/render-version-schema.sh | bash > $BASH_ENV
          source $BASH_ENV

examples:
  goreleaser:
    description: Build pipeline. Please check https://github.com/ory/meta/blob/master/docs/releasing.md
    usage:
      version: 2.1
      orbs:
        foo: ory/goreleaser@0.0.0
      workflows:
        release:
          jobs:
            - goreleaser/release
        test:
          jobs:
            - goreleaser/test
        release-dry:
          jobs:
            - goreleaser/release-dry
