version: 2.1
description: Run OSS Sonatype nancy

executors:
  default:
    docker:
      -
        image: circleci/golang:1.14
        environment:
          - GO111MODULE=on

jobs:
  test:
    executor: default
    steps:
      - checkout
      - run: curl -L -o $GOPATH/bin/nancy https://github.com/sonatype-nexus-community/nancy/releases/download/v0.2.6/nancy-linux.amd64-v0.2.6 && chmod +x $GOPATH/bin/nancy
      # exclude hashicorp/consul vulnerabilities because we don't use it (referenced by old viper)
      - run: go list -m all | nancy -quiet -exclude-vulnerability fc041c7e-0c64-4b74-991e-64196a704ace,2bfd5f1a-e9b5-4a04-b4e8-15091e145845,40365e0e-8b3c-4252-8124-dbbec0a45dfe

examples:
  nancy:
    description: Test go.mod for CVEs using nancy
    usage:
      version: 2.1
      orbs:
        foo: ory/nancy@0.0.1
      workflows:
        test:
          jobs:
            - nancy/test
