name: 'Releaser'
description: 'Release automation action'
inputs:
  token:
    description: Personal access token
    required: false
    default: ${{ github.token }}
  goreleaser_key:
    description: GoReleaser Pro license key
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ inputs.token }}
        fetch-depth: 0

    - run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"

        if [[ ! -e package.json ]]; then
          echo '{"private": true, "version": "0.0.0"}' > package.json
          git add package.json
        else
          echo "package.json exists and needs not be written"
        fi

        echo 'notes='"$(mktemp).md" >> $GITHUB_ENV
      shell: bash

    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16'

    - uses: actions/checkout@v2
      with:
        repository: ory/changelog
        path: changelog
        token: ${{ inputs.token }}

    - env:
        CURRENT_TAG: ${{ github.ref_name }}
      run: |
        npm --no-git-tag-version version "$CURRENT_TAG"

        (
          cd "$GITHUB_WORKSPACE/changelog";
          npm i
        )

        npx conventional-changelog-cli@v2.1.1 --config "changelog/index.js" -r 2 -o "$notes"

        if [[ "$OSTYPE" == "darwin"* ]]; then
          sed -i '' '/^# /d' "$notes"
        else
          sed -i '/^# /d' "$notes"
        fi

        npx prettier -w "$notes"
        git reset --hard HEAD
      shell: bash

    - env:
        GORELEASER_CURRENT_TAG: ${{ github.ref_name }}
        GORELEASER_KEY: ${{ inputs.goreleaser_key }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        cat "$notes"
        # clean up ory/changelog checkout
        rm -rf changelog

        docker pull --platform linux/amd64 oryd/xgoreleaser:latest
        docker run --mount type=bind,source="$(pwd)",target=/project \
            --platform linux/amd64 \
            -e GORELEASER_KEY=$GORELEASER_KEY \
            -e GITHUB_TOKEN=$GITHUB_TOKEN \
            -e GORELEASER_CURRENT_TAG=$GORELEASER_CURRENT_TAG \
            -v /var/run/docker.sock:/var/run/docker.sock \
            oryd/xgoreleaser:latest release --release-header <(cat "$notes") --rm-dist --timeout 60m --parallelism 1

        git add -A
        git stash || true
        git checkout master || true
        git stash pop || true
        git commit -a -m "autogen: update release artifacts" || true
        git pull origin master --rebase || true
        git push origin HEAD:master || true
      shell: bash
