name: 'Newsletter'
description: 'Newsletter draft/send automation'
inputs:
  mailchimp_api_key:
    description: Mailchimp API key
    required: true
  mailchimp_list_id:
    description: Mailchimp list ID
    required: true
  mailchmip_segment_id:
    description: Mailchimp segment ID
    required: true
  draft:
    description: Set this to 'false' to send
    required: false
    # not a boolean! ref: https://github.com/actions/runner/issues/1483
    default: 'true'
  ssh_key:
    description: SSH private key used to fetch the repository
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        mkdir -p /home/runner/.ssh
        ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
        echo "${{ inputs.ssh_key }}" > /home/runner/.ssh/github_actions
        chmod 600 /home/runner/.ssh/github_actions
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add /home/runner/.ssh/github_actions
        git config --global core.sshCommand "ssh -i /home/runner/.ssh/github_actions"
      shell: bash
    - env:
        MAILCHIMP_LIST_ID: ${{ inputs.mailchimp_list_id }}
        MAILCHIMP_SEGMENT_ID: ${{ inputs.mailchmip_segment_id }}
        MAILCHIMP_API_KEY: ${{ inputs.mailchimp_api_key }}
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      run: |
        bash <(curl https://raw.githubusercontent.com/ory/meta/master/install.sh) -b . ory
        if [[ "${{ inputs.draft }}" == "false" ]]; then
          # production run
          ./ory dev release notify send "${MAILCHIMP_LIST_ID}"
        elif [[ "${{ inputs.draft }}" == "true" ]]; then
          # draft run
          ./ory dev release notify draft --segment "${MAILCHIMP_SEGMENT_ID}" "${MAILCHIMP_LIST_ID}"
          ./ory dev release notify send --dry "${MAILCHIMP_LIST_ID}"
        else
          echo "inputs.draft should be either 'true' or 'false'"
          exit 1
        fi
      shell: bash
