name: Tests

on:
  pull_request:
    types:
      - opened
      - reopened
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - id: cache-node
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: conventional_commit_config/node_modules
          key:
            ${{ runner.os }}-cococo-node-${{
            hashFiles('conventional_commit_config/package-lock.json') }}
      - run: cd authors && make test
      - run: cd conventional_commit_config && make test
      - run: cd changelog && make test
      - run: cd licenses && make test
