name: Tests

on:
  pull_request:
    types:
      - opened
      - reopened
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: cache-node
        uses: actions/cache@v3
        with:
          path: conventional_commit_config/node_modules
          key:
            ${{ runner.os }}-cococo-node-${{
            hashFiles('conventional_commit_config/package-lock.json') }}
      - run: npm ci --legacy-peer-deps
        if: steps.cache-node.outputs.cache-hit != 'true'
      - run: cd conventional_commit_config && npm run test
