name: Tests

on:
  pull_request:
    types:
      - opened
      - reopened
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: cache-node
        uses: actions/cache@v3
        with:
          path: conventional_commit_config/node_modules
          key:
            ${{ runner.os }}-cococo-node-${{
            hashFiles('conventional_commit_config/package-lock.json') }}
      - run: cd conventional_commit_config && make test
      - run: cd changelog && make test
